name: bond_mobile
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    
  auto_route: ^5.0.1
  shared_preferences: ^2.0.0-dev.9
  flutter_native_splash: ^2.2.10+1
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.0.2
  flutter_contacts: ^1.1.5
  vibration: ^1.8.4

dev_dependencies:
  auto_route_generator: 5.0.1
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
